name: Testing docker compose

on:
  workflow_dispatch:

env:
  PG_URL: postgres://postgres:postgres@localhost:5433/postgres
  MONGO_URL: mongodb://127.0.0.1:27018/test
  PG_HOST: 127.0.0.1
  PG_NAME: postgres
  PG_PASSWORD: postgres
  PG_PORT: 5433
  PG_USER: postgres

jobs:
  be:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ğŸ— Setup docker compose
        uses: ./.github/actions/docker-compose

      - name: ğŸ— Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: âœ… Lint packages
        run: pnpm run -w lint

      - name: ğŸ‘· Build packages
        run: pnpm run -w build

      - name: Start BE
        run: pnpm --filter be start

      - name: Request to backend
        run: curl http://127.0.0.1:4000
