name: Test setup
on:
  workflow_dispatch:

jobs:
  test-setup:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ğŸ— Setup monorepo
        uses: ./.github/actions/setup-monorepo
