name: Test server starts in ci

on:
  workflow_dispatch:

jobs:
  be:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ğŸ— Setup docker compose
        uses: ./.github/actions/docker-compose

      - name: ğŸ— Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'

      - name: âœ… Lint packages
        run: pnpm run -w lint

      - name: ğŸ‘· Build packages
        run: pnpm run -w build

      - name: Request to backend
        run: http://127.0.0.1:4000
